name: readworkflow
on:
  push:
jobs:
 react-job:
  runs-on: ubuntu-latest
  steps:
   - name: Clone Code
     uses: actions/checkout@v3
   - name: Instal NodeJS
     uses: actions/setup-node@v3 
     with:
      node-version: '18'
   - name: Installing Dependenciese
     run: npm ci
   - name: Run Tests
     run: npm test
   